framework:
  messenger:
    transports:
      rabbitmq.subnet.event:
        serializer: messenger.transport.symfony_serializer
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

    routing:
      UnBlockerService\Domain\Subnet\Message\EventMessage: rabbitmq.subnet.event

when@test:
  framework:
    messenger:
      transports:
        rabbitmq.subnet.transition_event: 'in-memory://'
