parameters:
  env(MONOLOG_LOG_LEVEL): debug
  monolog.logger.level: "%env(MONOLOG_LOG_LEVEL)%"

when@dev: &when@dev
  monolog:
    channels:
      # Main channels
      - deprecation
      - error
      - event
      - doctrine
      - console
      - messenger
      - security
      # Custom channels
      - action
      - handler
      - publisher
      - downloader
      - subnet_manipulator
      - listener
      - exception

    handlers:
      # Main loggers
      main:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.main.log"
        channels:
          - "!action"
          - "!handler"
          - "!publisher"
          - "!subnet_manipulator"
          - "!listener"
          - "!exception"
      deprecation:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.deprecation.log"
        channels:
          - deprecation
      error:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.error.log"
        channels:
         - error
      event:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.event.log"
        channels:
          - event
      doctrine:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
        channels:
          - doctrine
      console:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.console.log"
        channels:
          - console
      messenger:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.messenger.log"
        channels:
          - messenger
      security:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.security.log"
        channels:
          - security
      # Custom loggers
      action:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.action.log"
        channels:
          - action
      handler:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.handler.log"
        channels:
          - handler
      publisher:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.publisher.log"
        channels:
          - publisher
      downloader:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.downloader.log"
        channels:
          - downloader
      subnet_manipulator:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.subnet_manipulator.log"
        channels:
          - subnet_manipulator
      listener:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.listener.log"
        channels:
          - listener
      exception:
        level: "%monolog.logger.level%"
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.exception.log"
        channels:
          - exception

when@prod:
  <<: *when@dev
  monolog:
    handlers:
      # Stdout logger
      stdout:
        type: stream
        level: "%monolog.logger.level%"
        path: php://stdout
        formatter: "monolog.formatter.json"

when@test:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
