framework:
  serializer:
    enable_attributes: true
    circular_reference_handler: UnBlockerService\Infrastructure\Symfony\Serializer\CircularReferenceHandler
    default_context:
      datetime_format: !php/const DateTimeInterface::RFC3339_EXTENDED
