services: &services
  _defaults: &defaults
    autowire: true
    autoconfigure: true

  UnBlockerService\:
    resource: '../src/**'
    exclude:
      - '../src/**/{Attribute,Util,Traits,Helper,Request,Response,Contract,ValueObject,Enum,DTO,Model,Entity,Message,Event,Data,Specification,Exception,UseCase,CompilerPass,DependencyInjection,Tests}'
      - '../src/**/{*Kernel.php}'

when@test:
  services:
    <<: *services
    _defaults:
      <<: *defaults
      public: true

    Symfony\Contracts\HttpClient\HttpClientInterface:
      synthetic: true
